WIP: Fix #641 by using environment variables to specify which gfx targets to compile
rocm-arch/rocm-arch pull request #650
Opened 2022-02-11 17:34 UTC by Ta180m

This is a work-in-progress implementation of my idea for fixing #641. Does anyone know of a better way to override the cmake variables other than using `sed` to modify `CMakeLists.txt`?

2022-02-14 15:55 UTC, throwm8 commented
You can just pass -DAMDGPU_TARGETS=${AMDGPU_TARGETS} to cmake. I used this(with the variable replaced with my gpu's arch)  to speed up the builds of rocFFT and rocBLAS so it should do what you desire.

2022-02-14 16:17 UTC, Ta180m commented
> You can just pass -DAMDGPU_TARGETS=${AMDGPU_TARGETS} to cmake. I used this(with the variable replaced with my gpu's arch) to speed up the builds of rocFFT and rocBLAS so it should do what you desire.

Thank you for the suggestion! I'll modify my PR to that instead.

2022-03-01 02:15 UTC, Ta180m commented
The commit history is currently very messy because I've had to constantly merge the upstream master branch into mine to get the latest commits, but the maintainers can squash merge to clean it up when they merge this PR.

2022-03-07 15:26 UTC, acxz requested changes
I actually don't think this is a bad idea, however, I want to be a more strict with you if that's okay.

1) Can you add the link to the line of code where each project uses the `ADMGPU_TARGETS` variable in the extended commit message? This is just to make sure that upstream uses this variable and we can keep track of it if they ever change it.
2) Can you also point to what targets `-all` gets expanded to?
3) When updating PKGBUILDs please bump the pkgrel and update the `.SRCINFO`. Search these terms in the archwiki for more info
4) Also go ahead and give `squashing` yourself a try! It's not that bad and you'll learn something!

2022-03-07 16:21 UTC, Ta180m commented
>     3. When updating PKGBUILDs please bump the pkgrel and update the `.SRCINFO`. Search these terms in the archwiki for more info

Are you sure you want me to bump the pkgrel? Wouldn't that make most people do an unnecessary rebuild?

2022-03-07 17:08 UTC, acxz approved these changes
Thanks for the clean up, yeah you are right we don't have to update the pkgrel.

This looks like a nice qol change for individuals compiling this PKGBUILDs. I think when we our binary stack up and running again on arch4edu then this variable should be empty, but for people compiling just for their own machine I like this.

@tpkessler I'll let you have the final say/merge on this.

2022-03-17 18:16 UTC, Ta180m commented
@tpkessler Any other changes that you want me to make to this PR?

2022-03-18 09:01 UTC, tpkessler commented
This is looking good @Ta180m! Could you please open a separate issue with the list of `AMDGPU_TARGETS` you added to the commit message? This makes it easier to keep track of changes by AMD.

2022-03-18 09:02 UTC, merged

2022-03-18 15:07 UTC, tpkessler commented
> Can you also point to what targets -all gets expanded to?

I had to reintroduce the default targets. Otherwise the package building fails at the linking step.

2022-03-18 18:28 UTC, Ta180m commented
> > Can you also point to what targets -all gets expanded to?
> 
> I had to reintroduce the default targets. Otherwise the package building fails at the linking step.

Which packages were you having trouble building without the default targets? I didn't have any issues.

2022-03-20 19:00 UTC, tpkessler commented
Let's continue the discussion here https://github.com/rocm-arch/rocm-arch/discussions/695