Re-enable support for gfx800
rocm-arch/rocm-arch pull request #742
Opened 2022-04-06 07:45 UTC by John-Gee

Hello,

As discussed in #741, this should have minimum impact outside of enabling gfx800 cards again.

I'm open to any change done by me or you of course.

Thank you!

2022-04-06 07:46 UTC, John-Gee commented
Should this somehow be marked as unsupported by AMD though?

2022-04-06 09:43 UTC, JP-Ellis commented
While you included the name and hash of the patch, you didn't commit the file nor did you include the URL where it came from.  I'm guessing you used [this patch file](https://github.com/xuhuisheng/rocm-build/blob/feature/build/patch/31.rocm-opencl-runtime-rocclr-gfx803-1.patch)?

Probably best to include the file directly in the commit along with a comment describing where it came from.  This will prevent upstream changes in the patch file from breaking the build, but still makes it easy to find the new relevant patch.

2022-04-06 10:00 UTC, John-Gee commented
Woops, my apologies, and I actually checked that the PR looked fine but didn't realize the file was missing... Sorry!

I actually had already done the other part, I hope that's the way you were thinking.
Thanks for this!

2022-04-06 14:33 UTC, acxz commented
> Should this somehow be marked as unsupported by AMD though?

No need, even though many of our users try to use unsupported ROCm cards, we still try to help & debug & contribute based on them.

We'll leave the issue open with the patched label to denote we are doing something different from upstream AMD, however.

2022-04-06 14:37 UTC, acxz requested changes
Can you update the [pkgrel](https://wiki.archlinux.org/title/PKGBUILD#pkgrel) and the [.SRCINFO](https://wiki.archlinux.org/title/.SRCINFO) file?
See: https://github.com/rocm-arch/rocm-arch/#contributing

2022-04-07 00:25 UTC, John-Gee commented
Done!

Thank you!

2022-04-07 17:20 UTC, tpkessler commented on rocm-opencl-runtime/PKGBUILD
> +	patch -p1 -i "$srcdir/enable-gfx800.patch"
Could you please add a link to the relevant discussion upstream @JP-Ellis suggested?

2022-04-07 17:21 UTC, tpkessler commented
Thanks for working on this @John-Gee! I will merge this after you will have taken care of the comments above.

2022-04-07 21:38 UTC, John-Gee commented
Hey,

I am not on my computer so I'll do the changes later, but isn't the link in
the patch enough or do you want it in both the patch and PKGBUILD or just
the latter?

Thanks for your help!


On Thu, Apr 7, 2022, 10:22 AM Torsten Keßler ***@***.***>
wrote:

> Thanks for working on this @John-Gee <https://github.com/John-Gee>! I
> will merge this after you will have taken care of the comments above.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rocm-arch/rocm-arch/pull/742#issuecomment-1092003607>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMR5AU5GAQNEOUWYRJCIATVD4KTPANCNFSM5SVD2NIA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-09 07:44 UTC, tpkessler commented
LGTM! Thank you very much @John-Gee.

2022-04-09 07:44 UTC, merged

2022-04-09 08:47 UTC, John-Gee commented
Thank you all!